name: qywx

on:
  workflow_dispatch:

jobs:
  send_msg:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      QYWX_WEBHOOK: ${{ secrets.QYWX_WEBHOOK }}
    steps:
    - name: main
      uses: x-cmd/action@main
      with:
        code: |
          x qywx --cfg webhook='${{ secrets.QYWX_WEBHOOK }}'
          x qywx send aa
