name: qywx

on:
  workflow_dispatch:

jobs:
  qywx:
    runs-on: ubuntu-latest
    steps:
      - name: main
        env:
          QYWX_WEBHOOK: ${{ secrets.QYWX_WEBHOOK }}
          JOB_STATUS: ${{ job.status }}
        run: |
          eval "$(curl https://get.x-cmd.com)"

          if [ "$JOB_STATUS" = "success" ]; then
            TITLE="✅ 发布成功"
          else
            TITLE="❌ 发布失败"
          fi

          MESSAGE="## $TITLE"
          x qywx --cfg webhook='${{ secrets.QYWX_WEBHOOK }}'
          x qywx send --markdown "$MESSAGE"
