name: CI with WeChat Work Notification

on:
  workflow_dispatch:

jobs:
  qywx:
    runs-on: ubuntu-latest
    steps:
      - name: main
        env:
          QYWX_WEBHOOK: ${{ secrets.QYWX_WEBHOOK }}
        run: |
          eval "$(curl https://get.x-cmd.com)"
          x qywx --cfg webhook='${{ secrets.QYWX_WEBHOOK }}'
          x qywx send aa
