name: qywx

on: [push]

jobs:
  build:
    runs-on: ubuntu-lates
    env:
      qywx_webhook: ${{ secrets.QYWX_WEBHOOK }}

    steps:
    - name: main
      uses: x-cmd/action@main

      with:
        run: |
          x qywx --cfg webhook=$qywx_webhook
          x qywx send aa
