name: qywx

on:
  workflow_dispatch:

jobs:
  qywx:
    runs-on: ubuntu-latest
    steps:
      - name: main
        env:
          QYWX_WEBHOOK: ${{ secrets.QYWX_WEBHOOK }}
          JOB_STATUS: ${{ job.status }}
        run: |
          eval "$(curl https://get.x-cmd.com)"

          if [ "$JOB_STATUS" = "success" ]; then
            TITLE="✅ x-cmd 新版本发布成功"
          else
            TITLE="❌ x-cmd 新版本发布失败"
          fi

          MESSAGE="## $TITLE <@all>
          已安装 **x-cmd** 的用户，快使用 `x upgrade` 升级吧！
          >官网: [https://x-cmd.com](https://x-cmd.com)
          >Github: [github.com/x-cmd/x-cmd](https://github.com/x-cmd/x-cmd)
          ![x-cmd](https://codeberg.org/curry798/tea/raw/branch/main/og.png)"
          
          x qywx --cfg webhook='${{ secrets.QYWX_WEBHOOK }}'
          x qywx send --markdown "$MESSAGE"
