name: qywx

on:
  workflow_dispatch:

jobs:
  send_msg:
    runs-on: ubuntu-lates
    timeout-minutes: 20
    env:
      qywx_webhook: ${{ secrets.QYWX_WEBHOOK }}
      github_token: ${{ secrets.TOKEN }}
      git_user: curry798
      git_email: huangshengtao@x-cmd.com
    steps:
    - name: main
      uses: x-cmd/action@main
      with:
        code: |
          x qywx --cfg webhook='${{ secrets.WEBHOOK_URL }}'
          x qywx send aa
